# Conda environment dev-tf
name: dev-tf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipykernel
